apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: dionysbiz
    provider: github
    repository: testingress2
  name: dionysbiz-testingress2
spec:
  description: Imported application for dionysbiz/testingress2
  httpCloneURL: https://github.com/dionysbiz/testingress2.git
  org: dionysbiz
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: testingress2
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/dionysbiz/testingress2.git
