apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: dionysbiz
    provider: github
    repository: testlb1
  name: dionysbiz-testlb1
spec:
  description: Imported application for dionysbiz/testlb1
  httpCloneURL: https://github.com/dionysbiz/testlb1.git
  org: dionysbiz
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: testlb1
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/dionysbiz/testlb1.git
