apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: dionysbiz
    provider: github
    repository: afterremovehrepo
  name: dionysbiz-afterremovehrepo
spec:
  description: Imported application for dionysbiz/afterremovehrepo
  httpCloneURL: https://github.com/dionysbiz/afterremovehrepo.git
  org: dionysbiz
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: afterremovehrepo
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/dionysbiz/afterremovehrepo.git
