apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: dionysbiz
    provider: github
    repository: testnode
  name: dionysbiz-testnode
spec:
  description: Imported application for dionysbiz/testnode
  httpCloneURL: https://github.com/dionysbiz/testnode.git
  org: dionysbiz
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: testnode
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/dionysbiz/testnode.git
