apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: dionysbiz
    provider: github
    repository: afterclean
  name: dionysbiz-afterclean
spec:
  description: Imported application for dionysbiz/afterclean
  httpCloneURL: https://github.com/dionysbiz/afterclean.git
  org: dionysbiz
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: afterclean
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/dionysbiz/afterclean.git
