apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: ram4444
    provider: github
    repository: testkindnode5
  name: ram4444-testkindnode5
spec:
  description: Imported application for ram4444/testkindnode5
  httpCloneURL: https://github.com/ram4444/testkindnode5.git
  org: ram4444
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: testkindnode5
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/ram4444/testkindnode5.git
