apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: ram4444
    provider: github
    repository: testafterdelete
  name: ram4444-testafterdelete
spec:
  description: Imported application for ram4444/testafterdelete
  httpCloneURL: https://github.com/ram4444/testafterdelete.git
  org: ram4444
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: testafterdelete
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/ram4444/testafterdelete.git
