apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: ram4444
    provider: github
    repository: testj1
  name: ram4444-testj1
spec:
  description: Imported application for ram4444/testj1
  httpCloneURL: https://github.com/ram4444/testj1.git
  org: ram4444
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: testj1
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/ram4444/testj1.git
