apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: ram4444
    provider: github
    repository: testnoip3
  name: ram4444-testnoip3
spec:
  description: Imported application for ram4444/testnoip3
  httpCloneURL: https://github.com/ram4444/testnoip3.git
  org: ram4444
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: testnoip3
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/ram4444/testnoip3.git
